### ISSUE TITLE
[Chetna Report] Line List of Children with Nutritional Status

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#17]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=2020518397

##### QA Comments - 
- Filter - Put Start date before End Date. Done
- Age of child, keep it in Years and Months like 1 Year 2 Months. Done

**Comment by vindeolal** [comment]
report link : https://reporting.openchs.org/question/504
