### ISSUE TITLE
[Chetna Report] Child Immunisation Due List

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#18]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=2020518397

##### QA Comments -
- What about expired vaccines?     Only Due, Overdue and Critical are shown
- Age of child (In Years and Months).  Fixed.

**Comment by vindeolal** [comment]
report link : https://reporting.openchs.org/question/508
