### ISSUE TITLE
[Chetna Report] Child Immunisation Completed List

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#19]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=2020518397

##### QA Comments - 
- For one vaccination there are two or more rows showing. for eg: Jai Prakash | Pentavalent 1, this vaccine is showing 3 times.  Fixed
- Exited/Voided children are excluded? Please check once.  Yes
- Age of child is in Months or Year. Keep it like "1 Year 2 Months"?  Fixed
- Age is the current age or age at the time of vaccination.  Current Age
- Age calculation is wrong.

**Comment by vindeolal** [comment]
report link : https://reporting.openchs.org/question/507
