### ISSUE TITLE
[Chetna Report] List of pregnant woman

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#22]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=2020518397

##### QA Comments - 
- Replace "first name" with "Name of Pregnant Woman". Done
- Remove column "Current Month of Pregnancy". Done

**Comment by vindeolal** [comment]
report link : https://reporting.openchs.org/question/502
