### ISSUE TITLE
[Chetna Report] List of lactating mothers with knowledge about breastfeeding practices

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#23]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=2020518397

##### QA Comment - 
- "Till which age your child has breastfed exclusively?" - **DONE**
- "When did you start giving complimentary food to the child?" - **DONE**
   There is a change in these two columns. Changes are highlighted in the sheet.
- Check Age of Child. It seems to be wrong. Also, mention that age is in years and Months like "1 year 2 months". - **DONE**

**Comment by vindeolal** [comment]
report link : https://reporting.openchs.org/question/503
