### ISSUE TITLE
[Chetna] feedback after Monthly monitoring testing

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#27]
##### PW Enrolment - https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=60382782
- 22.1 Question (Highlighted in the sheet) - In this question "Other" is unique option. But Don't Know should be Unique option. -- DONE

##### Monthly monitoring -https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=731876386
- Translation (highlighted in the sheet)
- 9. Number of checkups - Validate from Enrolment. They should not be able to fill less number in Monthly monitoring. -- DONE
- BP Systolic and Diastolic Validation (<= 50) -- DONE
- HB Range (>=11) instead of (12-15.5) -- DONE

##### Cancel form - https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=952900991
- Translation -- DONE

**Comment by arjunk** [comment]
@garimadosar5  APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-28bc4-2019-09-12-15-05-49.apk

**Comment by garimadosar5** [comment]
@arjunk 

##### QA comments - 2
- HB Range (>=11) instead of (>11) --Not DONE
- PW Monthly Monitoring - Place of ANC check-up - (last option) - ANC તપાસ કરાવી નથી

**Comment by arjunk** [comment]
@garimadosar5 fixed the 2 issues. 
APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-31542-2019-09-13-17-37-22.apk
