### ISSUE TITLE
[Chetna] Feedback for Monthly monitoring - 2

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#28]
Monthly Monitoring Testing feedback- 

PW Enrolment - 

##### Monthly monitoring PW -
- Do you have done Antenatal check-up in this month? (Add this question) -- **Done**
- How many Antenatal checkups you had? (Remove this Question). -- **Done**
- Place of check-up (Add the condition and Remove one option - 'ANC Checkup not done') --**Done**--
- Add Translation for 'BP Systolic' and 'BP Systolic'. -- **Done**
- What information did she get in the month through educational session/home visits? (Check the translation) and add an option 'Does not remember' (Add translation also) and make this unique 
selection. -- The option Don't remember and translation was already there. made unique. --**DONE**
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=731876386

##### Child monthly monitoring
- What information she got in the month through educational session/home visits? (Check the translation) and add an option 'Does not remember' (Add translation also) and make this unique selection. And Make the Question Multi-select. -- **Done**
- Type of packaged food gets to the child from outside (there is a change in the translation). -- **Done**
- Did you give water to the child in this month? (Add the condition in this question). -- **Done**
-  Does child breastfeed exclusively? (Condition is not working). -- seems to be working fine
- How many times do you breastfeed to your child? (Remove the condition) and Add one more option "Not breastfeeding the child". -- **Done**
- From which month child got complimentary food? (Translation for the options of the question is not as per in the sheet). -- **Done**
- Morbidity profile (Change the translation for the group). -- **Done**
- Type of home-based food gets to the child (Option/ Translation for the options for this question needs to be changed) --**Done**
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=1061724858

Visit Scheduling is breaking. Eg: Cases 'Ranjan Patel' and 'Visit Scheduling'  and 'Shayli Shah'. -- Done

##### Platform - 
- Individual list - 
 Age - વર્ષ (Translation) -- Done
- Age of child show in month instead of Weeks. -- Done

**Comment by arjunk** [comment]
@garimadosar5 Deployed changes to staging. Also APK with translations available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-1583-2019-09-20-15-45-16.apk

**Comment by arjunk** [comment]
@garimadosar5 Latest APK Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-86087-2019-09-20-18-41-56.apk
This has the date weeks fix also.

**Comment by garimadosar5** [comment]
@arjunk 
- What information did she get in the month through educational session/home visits? 
Please correct the translation. The translation is there but this is not the same as they have given.
