### ISSUE TITLE
[Chetna] Form Translation

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#3]
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=60382782

String not Translated - 
- Home Page -> Register -> Name of programs (Individual, Pregnancy)
- Home Page ->Filter, Individual, As on Date.
- Home Page -> Filter -> Area.
- Search Page -> Area
- Home Page -> Settings -> Location , Track Location.
**Individual Dashboard**
- Programs
             - Visits Planned
             - Enrolment Details
             - Completed Visits
- Profile
               - Relatives
               - Delete
               - No Relative Added
               - Registration Details
               - Registration Date
- In the app header form names are showing in English.

Stings are here: https://docs.google.com/spreadsheets/d/15U3nsIegWZQAtPL6Oa6Y9RG4EFQcPn7yDZODCmm4RXw/edit#gid=0

**Comment by nupoorkhandelwal** [comment]
I have added the strings given in the sheet.
