### ISSUE TITLE
[Chetna][Support] For child - Wrong nutritional status in Program summary 

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#33]
https://openchs.freshdesk.com/a/tickets/462

**Comment by vinayvenu** [comment]
Issue: ZScores were calculated based on enrolment date time, and not the time the visit took place. 

Solution
1. ZScores calculation is fixed. 
2. When we go live, all children will have incorrect zscores stored in their enrolment. This will autocorrect itself when we either create a new visit, or edit an existing visit for that child. Until then, please ignore the values shown on the program summary and the enrolment.

**Comment by garimadosar5** [comment]
@vinayvenu 

Keeping this to QA ready as data fix is pending.
