### ISSUE TITLE
[Chetna][Support] Line list of due cases for Monthly monitoring.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#34]
https://openchs.freshdesk.com/a/tickets/461
**Metabase report for a duelist of **
- Child Monthly Monitoring 
- Pregnant Woman Monthly Monitoring

List of all the Due visits - 
#### Name of Columns - Child Monthly Monitoring
- Name
- Name of Mother/Caretaker
- Date of Birth
- Age
- Area
-  Address
- Contact Number
- SChedule date `(earliest visit date-time)`

#### Name of Columns - Pregnant Woman Monthly Monitoring
- Name
- Date of Birth
- Age
- Area
-  Address
- Contact Number
- LMP
- Pregnancy Month
- Schedule date `(earliest visit date-time)`

**Filter -**
Area.
Start Date.
End Date.

Ref - Calcutta Kids "Due report".

**Comment by vindeolal** [comment]
@garimadosar5 
Child Monthly Monitoring Due List : https://reporting.openchs.org/question/562
Pregnant woman Due List : https://reporting.openchs.org/question/563
