### ISSUE TITLE
[Chetna][Report] A Graph of Trimester wise Number of pregnant women monthly monitoring done.

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#39]
https://openchs.freshdesk.com/a/tickets/480

**Comment by nupoorkhandelwal** [comment]
https://reporting.openchs.org/question/609

https://reporting.openchs.org/question/608

https://reporting.openchs.org/question/610

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
I am not able to understand this. Lets' do the dev box for this card tomorrow.

**Comment by garimadosar5** [comment]
Closing this card. ticked has been marked as closed.
