### ISSUE TITLE
[Chetna] Lactating Mother Enrolment

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#4]
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=113731661

##### QA Comment 
- "Information and knowledge about breastfeeding and complementary food" group, questions are not in the same order and there is an extra question "How much food should be given to the child?"
- Skip in Question 20 is not working. It does not show all the question seven child's age is more than 6 months.

**Comment by nupoorkhandelwal** [comment]
Pushed changes to staging
