### ISSUE TITLE
[Support] [CHETNA-SNEHA] Changes in Monthly Monitoring Pregnant Women

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#44]
https://openchs.freshdesk.com/a/tickets/510

https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=731876386

** Add condition of when not not to show for section >> Services availed during pregnancy **

**Comment by nupoorkhandelwal** [comment]
** Moved to staging environment**

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 
QA Notes - 
If TT1 and TT2 is given. In next visit, it again asks the question "TT injection given".

**Comment by nupoorkhandelwal** [comment]
** fixed on staging **

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 

This is working on staging. Move this on Prod.
