### ISSUE TITLE
[Chetna-Sneha][Report] Immunization of children up to 1 year of age

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#53]
Aggregate -- https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=67:67

Linelist -- https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=36:36

**Comment by garimadosar5** [comment]
QA Notes - 
On line list page, there is an extra filter showing
![Screen Shot 2020-12-11 at 12.58.36 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/3989c3f0-dac3-4c53-9d13-717cba1f2169)


It helps to show condition when someone navigates from aggregate report to linelist
