### ISSUE TITLE
[Chetna-Sneha][Report] Nutritional status of children up to 2 years

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#54]
Aggregate --
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=85:85

Linelist --
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=30:30

**Comment by garimadosar5** [comment]
QA Notes - 
The error message on date filter.
![Screen Shot 2020-12-07 at 12.46.54 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/29ee70af-abe9-4fdc-87e8-c3936a6a458e)
