### ISSUE TITLE
[Chetna-Sneha][Report]Cancel visit data

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#56]
https://docs.google.com/spreadsheets/d/1dBGaEtG7TtNvPMfqggM_NdXSAPGsQpqGZ7ijty-rAkA/edit#gid=1210980279&range=119:119

**Comment by garimadosar5** [comment]
QA Notes - 
- Indicator - "Total pregnant women visit scheduled", does not seem right.   **Fixed**
The number was showing 11. then I cancelled one visit and then it starts showing 12. It is counting cancel visit also.
![Screen Shot 2020-12-10 at 3.43.45 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/01e51e75-3bd3-464e-964e-48ece9d7fad4)

- The same is happening for Child visit.
