### ISSUE TITLE
[Chetna-Sneha] Monthly reports for field worker form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#59]
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=1384434222

Report --https://reporting.avniproject.org/question/1468
https://reporting.avniproject.org/question/1472

All these changes are on staging

- [x] New subject type -'Field Worker'

- [x] General encounter type for the new subject type -- 'Monthly monitoring report of field worker'

- [x]  Report to consume this data

**Comment by garimadosar5** [comment]
QA Notes - 
- New subject type says - **Monthly monitoring**. It seems like user need to fill this monthly basis. **Yes..its supposed to be filled every month**
The Individual will register once and then general encounter will be filled on monthly basis. **The users will be registered once and then the Register  access will be revoked. So only monthly reporting scheduled visits will be available for that user.**
- Reg form - First question says "Monthly Reporting name". It should say User name. **Its updated**
- When a new user gets register, first monthly reporting gets scheduled for same day next month. 
1. How will I fill the info from current month. 
2. Is it not get schedule on the last day of month?
Confirm and fix accordingly. **This has been discussed , this visit will be completed in the current month itself, 5 days prior. SO changed the scheduling date to 25th of that respective month.**
