### ISSUE TITLE
[CHETNA-SNEHA] Move offline reports from staging to production org

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#66]
- [ ]  We have offline indicator reports (two dashboards for each of the programs) on staging, need to move them to production.
This can be done via bundle download and upload.

**Comment by garimadosar5** [comment]
QA Notes - 
SYnc error.
![Screen Shot 2021-02-05 at 3.28.17 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/53cf146d-45c5-4168-9214-727ba954eeb1)

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 can you please test this on production org. Its working fine there.
