### ISSUE TITLE
[CHETNA-SNEHA] Year 2 changes/feedback after Go Live

### ISSUE THREAD

**Issue by nupoorkhandelwal** [OpenCHS/CHETNA-SNEHA#67]
https://docs.google.com/spreadsheets/d/1uAtEoR3xRooifh2f0F1cLk1-Y_E3TWribKwv6oH5PL4/edit#gid=1273553315

Next action items in the spreadsheet

- [x]  Need to remove exit cases from Offline indicators report

- [x] Remove voided individuals from Jasper reports

- [x] Add exit filters in all the jasper reports

- [x] Add start dates and end dates for Enrolment and Encounters separately in each of the Jasper reports

- [x]  "Linelist of children weight and nutritional status" add encounter dates for each corresponding weight & status. Also show data for 24 visits in the ascending order.

- [x] Aggregate report-Information about Breastfeeding practices" Make changes as suggested in the sheet. Check for options to be considered in each of the indicator.Add the new indicator mentioned.Also cross check for sum of the respective indicators to match the total.

- [x] Aggregate report -Information about pregnancy and ANC"Add another indicator in report mentioning "Pregnant women with place of delivery information not available"

- [ ] Share list of metabase reports- Need to archive the ones they dont need Or  not available in Japser or longitudinal export.

**Comment by sachsk** [comment]
- In all line list add exit status column

Report:-
- Cancel visit report:
     - [x]  Exit filter is missing.

     - [x]  linelist for schedule visit put appropriate title.

- info about breastfeeding practices:
     - [x]  Agg. number is not matching with the linelist.
          Children who have birth weight below 2.5Kg is 93 in aggg. and in line list it is 82. filter exit satus= no.

- immunization of child 
     - [x]  exit and area filter is not working
- Information about pregnant women and ANC services:
     - [x] Agg. number is not matching with the linelist.    
           completed 4 visit 28 in agg. and in line list it is 155 filter area= EWS 1-15.

**Comment by garimadosar5** [comment]
QA Notes - 
-  Formatting issue -  Case- Arjun Sanjaybhai Dantani
![Screen Shot 2021-02-16 at 5.41.45 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/35918f94-2edc-44c6-9463-1d53559c2ad3)
- Error when press NEXT PAGE in line list. (This is happening when any filter is applied.)
![Screen Shot 2021-02-16 at 5.43.15 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/cb4336b3-7778-4003-b50a-0c19cc312a88)
- Report - Immunization of children (Exit filter is working reverse) - This is happening for all the reports.
![Screen Shot 2021-02-16 at 5.53.29 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/312741d6-e712-407a-981f-f3c027f10bf6)
- Exit filter is not working for - Information about breastfeeding practices
