### ISSUE TITLE
[Chetna][Support] App is crashing on edit

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/CHETNA-SNEHA#72]
ticket - https://avni.freshdesk.com/a/tickets/1205

Video is attached in ticket.

**Comment by vindeolal** [comment]
It was happening due to data issue. Fixed the data for pregnant women enrolment. User will need to sync before they edit next time.
Script: https://github.com/avniproject/CHETNA-SNEHA/blob/master/migrations/FD1205.sql
